language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DVRAfAwVhegOjHtgbKeQIGl/HvTEjmNRjp4uLx6ZiaPebtrKUCuBs7zxYUshx64chq1cnHS6EA1zM1LGfxOgw6+9U4/GsFNt/jzSawJGJWjz8i5AVD03eDWJHMsF7YYHdTifdIx79vms5agIbWi4OGzeDg7KwvX99aKLAqcnpX1tCcSRJQNZsj+/YGTpfNPfGkJaKPudKAbs0RmZvbk5GJVZ/2Sgx33HJDRRjcqI2vqJa8BYJ953mM1WedgVBjYqvxHwPIKsC+h6X2tND9t6nNWNlpoByFs91LzFMgSNfG9d/0W7OpPpivn1NCtkeKtXbhZ3HBo6DPg6kGy8xKqZMTcd/VaGovO4hwMp0nNM4lT/sv1zJcJAsKtNbAtjxgoNVZts8xYgQhAmW6Dy3ABfCEzMKQ/8Xk3EbBYQwlx/8Fx0f/06FF5bjEX+1vY+LXk+4KoaAk51UcVwB0hlh0Kq9Pg8PjZyGCZ7K/XvY31ahJaJEBqBqcuMhp/YDKkTKvrtyDLvnIa/wUkT5Fju0nOj29LfW60mV0e3OJe5+wi22szeP48852A1U5qSRxMhsK+RuNU4QgigfvMniGML6tlRVLukk8eW5YepbKMll1SSRHNiCOiIYZ/1BHiP93qmPiiI4y2SPxWZH1MO6Es1+bUQpq1AV5sBq+BdvUMH62V+H38=
  app: trip-track-api
  on:
    repo: amandaherschleb/trip-tracker-api
    branch: master
